//Messages de page contact
export const ADD_MSG = "ADD_MSG";
export const FETCH_MSG_REQUEST = "FETCH_MSG_REQUEST"
export const FETCH_MSG_SUCCESS = "FETCH_MSG_SUCCESS"
export const FETCH_MSG_FAILURE = "FETCH_MSG_FAILURE"

//centers
export const FETCH_CENTER_REQUEST = "FETCH_CENTER_REQUEST"
export const FETCH_CENTER_SUCCESS = "FETCH_CENTER_SUCCESS"
export const FETCH_CENTER_FAILURE = "FETCH_CENTER_FAILURE"
export const ADD_CENTER = "ADD_CENTER"
export const ADD_PHARMACIE = "ADD_PHARMACIE"
export const DELETE_CENTER = "DELETE_CENTER"
export const FETCH_CENTER_BY_ID = "FETCH_CENTER_BY_ID"
export const UPDATE_CENTER="UPDATE_CENTER"
export const FETCH_CENTER_VACCIN_BY_ID="FETCH_CENTER_VACCIN_BY_ID"
//gouvernorat
export const FETCH_GOV_REQUEST = "FETCH_GOV_REQUEST"
export const FETCH_GOV_SUCCESS = "FETCH_GOV_SUCCESS"
export const FETCH_GOV_FAILURE = "FETCH_GOV_FAILURE"

//voluntaries
export const FETCH_VOL_REQUEST = "FETCH_VOL_REQUEST"
export const FETCH_VOL_SUCCESS = "FETCH_VOL_SUCCESS"
export const FETCH_VOL_FAILURE = "FETCH_VOL_FAILURE"
export const FETCH_VOL_By_Center_REQUEST = "FETCH_VOL_By_Center_REQUEST"
export const FETCH_VOL_By_Center_SUCCESS = "FETCH_VOL_By_Center_SUCCESS"
export const FETCH_VOL_By_Center_FAILURE = "FETCH_VOL_By_Center_FAILURE"
export const FETCH_VOL_BY_ID = "FETCH_VOL_BY_ID"
export const DELETE_VOL = "DELETE_VOL"
export const UPDATE_VOL="UPDATE_VOL"
export const ADD_VOL = "ADD_VOL"

// ville
export const FETCH_VILLE_REQUEST = "FETCH_VILLE_REQUEST"
export const FETCH_VILLE_SUCCESS = "FETCH_VILLE_SUCCESS"
export const FETCH_VILLE_FAILURE = "FETCH_VILLE_FAILURE"
//vaccin
export const FETCH_VACCIN_REQUEST = "FETCH_VACCIN_REQUEST"
export const FETCH_VACCIN_SUCCESS = "FETCH_VACCIN_SUCCESS"
export const FETCH_VACCIN_FAILURE = "FETCH_VACCIN_FAILURE"
export const ADD_VACCIN = "ADD_VACCIN"
export const ADD_CENTER_VACCIN = "ADD_CENTER_VACCIN"

export const DELETE_VACCIN = "DELETE_VACCIN"
export const FETCH_VACCIN_BY_ID = "FETCH_VACCIN_BY_ID"
export const UPDATE_VACCIN="UPDATE_VACCIN"

//jpo
export const FETCH_JPO_REQUEST = "FETCH_JPO_REQUEST"
export const FETCH_JPO_SUCCESS = "FETCH_JPO_SUCCESS"
export const FETCH_JPO_FAILURE = "FETCH_JPO_FAILURE"
export const FETCH_JPO_BY_ID = "FETCH_JPO_BY_ID"
export const ADD_JPO = "ADD_JPO"
export const DELETE_JPO = "DELETE_JPO"
export const LOCAL_STOCK = "LOCAL_STOCK"
export const AFFECT_CENTER_JPO = "AFFECT_CENTER_JPO"
export const FETCH_ALL_JPO_CENTERS_REQUEST = "FETCH_ALL_JPO_CENTERS_REQUEST"
export const FETCH_ALL_JPO_CENTERS_SUCCESS = "FETCH_ALL_JPO_CENTERS_SUCCESS"
export const FETCH_ALL_JPO_CENTERS_FAILURE = "FETCH_ALL_JPO_CENTERS_FAILURE"
export const FETCH_JPO_ONE_CENTER = "FETCH_JPO_ONE_CENTER"
export const DELETE_JPO_CENTERS = "DELETE_JPO_CENTERS"
//inscription
export const INSCRIPTION = "INSCRIPTION"

//Vaccin pour stat 
export const FETCH_VACSTAT_REQUEST = "FETCH_VACSTAT_REQUEST"
export const FETCH_VACSTAT_SUCCESS = "FETCH_VACSTAT_SUCCESS"
export const FETCH_VACSTAT_FAILURE = "FETCH_VACSTAT_FAILURE"






