export const ADD_MSG = "ADD_MSG";
//centers
export const FETCH_CENTER_REQUEST = "FETCH_CENTER_REQUEST"
export const FETCH_CENTER_SUCCESS = "FETCH_CENTER_SUCCESS"
export const FETCH_CENTER_FAILURE = "FETCH_CENTER_FAILURE"

//gouvernorat
export const FETCH_GOV_REQUEST = "FETCH_GOV_REQUEST"
export const FETCH_GOV_SUCCESS = "FETCH_GOV_SUCCESS"
export const FETCH_GOV_FAILURE = "FETCH_GOV_FAILURE"