export const ADD_MSG = "ADD_MSG";
//centers
export const FETCH_CENTER_REQUEST = "FETCH_CENTER_REQUEST"
export const FETCH_CENTER_SUCCESS = "FETCH_CENTER_SUCCESS"
export const FETCH_CENTER_FAILURE = "FETCH_CENTER_FAILURE"
export const ADD_CENTER = "ADD_CENTER"
export const DELETE_CENTER = "DELETE_CENTER"

//gouvernorat
export const FETCH_GOV_REQUEST = "FETCH_GOV_REQUEST"
export const FETCH_GOV_SUCCESS = "FETCH_GOV_SUCCESS"
export const FETCH_GOV_FAILURE = "FETCH_GOV_FAILURE"

// ville
export const FETCH_VILLE_REQUEST = "FETCH_VILLE_REQUEST"
export const FETCH_VILLE_SUCCESS = "FETCH_VILLE_SUCCESS"
export const FETCH_VILLE_FAILURE = "FETCH_VILLE_FAILURE"